FROM harbor.emotibot.com/bfop/bfop-automation:base

COPY docker/conf/nginx.conf /etc/nginx/nginx.conf
COPY docker/conf/default.conf /etc/nginx/conf.d/default.conf

WORKDIR /usr/share/nginx/html

COPY docker/entrypoint.sh .
COPY build .
COPY / ./appen-praise

RUN cd appen-praise && npm install

ENTRYPOINT ["./entrypoint.sh"]
